export const CATEGORIES = ['Shirts', 'Pants', 'Sarees', 'Chudithar', 'Kids', 'Innerwear', 'Others'];
export const PREDEFINED_COLORS = [
    { name: 'Red' }, { name: 'Blue' }, { name: 'Green' }, { name: 'Black' }, { name: 'White' },
    { name: 'Yellow' }, { name: 'Orange' }, { name: 'Purple' }, { name: 'Pink' }, { name: 'Brown' },
    { name: 'Grey' }, { name: 'Maroon' }, { name: 'Navy Blue' }, { name: 'Sky Blue' }, { name: 'Gold' },
    { name: 'Silver' }, { name: 'Beige' }, { name: 'Cream' }, { name: 'Olive' }, { name: 'Teal' },
    { name: 'Mustard' }, { name: 'Lavender' }, { name: 'Peach' }, { name: 'Coral' }, { name: 'Burgundy' },
    { name: 'Charcoal' }, { name: 'Indigo' }, { name: 'Magenta' }, { name: 'Cyan' }, { name: 'Lime' },
    { name: 'Turquoise' }, { name: 'Violet' }, { name: 'Rust' }, { name: 'Tan' }, { name: 'Khaki' }
];
export const SHIRT_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];

export const TRANSLATIONS = {
  en: {
    appName: 'SEV CREATIONS',
    dashboard: 'Dashboard',
    stock: 'Stock',
    accounts: 'Accounts',
    profile: 'Profile',
    settings: 'Settings',
    addStock: 'Add Stock',
    itemName: 'Item Name',
    price: 'Price',
    category: 'Category',
    photo: 'Photo',
    color: 'Color',
    size: 'Size',
    save: 'Save',
    update: 'Update',
    editTransaction: 'Edit Transaction',
    addTransaction: 'Add Transaction',
    income: 'Income',
    expense: 'Expense',
    partyName: 'Party Name',
    resetLinkSent: 'Reset link sent!',
    businessName: 'Business Name',
    address: 'Address',
    contact: 'Contact Number',
    currencySymbol: 'Currency Symbol',
    currencyCode: 'Currency Code',
    language: 'Language',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings Saved!',
    setupServer: 'Setup Server',
    logout: 'Logout',
    clearData: 'Clear Data',
    restoreData: 'Restore Data',
    deleteAccount: 'Delete Account',
    confirmDelete: 'Are you sure you want to delete your account? This action cannot be undone.',
    delete: 'Delete',
    cancel: 'Cancel',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    notifications: 'Notifications',
    enableNotifications: 'Enable Notifications',
    disableNotifications: 'Disable Notifications',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    about: 'About',
    version: 'Version 1.0.0',
    copyright: '© 2023 Viyabaari. All rights reserved.',
    poweredBy: 'Powered by Viyabaari',
    madeWithLove: 'Made with ❤️ in India',
    contactSupport: 'Contact Support',
    reportBug: 'Report Bug',
    shareApp: 'Share App',
    rateApp: 'Rate App',
    followUs: 'Follow Us',
  },
  ta: {
    appName: 'SEV CREATIONS',
    dashboard: 'முகப்பு',
    stock: 'சரக்கு',
    accounts: 'கணக்கு',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    addStock: 'சரக்கு சேர்',
    itemName: 'பொருள் பெயர்',
    price: 'விலை',
    category: 'வகை',
    photo: 'படம்',
    color: 'நிறம்',
    size: 'அளவு',
    save: 'சேமி',
    update: 'புதுப்பி',
    editTransaction: 'பரிவர்த்தனையைத் திருத்து',
    addTransaction: 'பரிவர்த்தனை சேர்',
    income: 'வருமானம்',
    expense: 'செலவு',
    partyName: 'நபர் பெயர்',
    resetLinkSent: 'மீட்டெடுப்பு இணைப்பு அனுப்பப்பட்டது!',
    businessName: 'வியாபார பெயர்',
    address: 'முகவரி',
    contact: 'தொடர்பு எண்',
    currencySymbol: 'நாணய குறியீடு',
    currencyCode: 'நாணய குறியீடு',
    language: 'மொழி',
    saveSettings: 'அமைப்புகளை சேமி',
    settingsSaved: 'அமைப்புகள் சேமிக்கப்பட்டது!',
    setupServer: 'சர்வர் அமை',
    logout: 'வெளியேறு',
    clearData: 'தரவை அழி',
    restoreData: 'தரவை மீட்டெடு',
    deleteAccount: 'கணக்கை நீக்கு',
    confirmDelete: 'நிச்சயமாக உங்கள் கணக்கை நீக்க விரும்புகிறீர்களா? இந்த செயலை மாற்ற முடியாது.',
    delete: 'நீக்கு',
    cancel: 'ரத்து',
    theme: 'தீம்',
    light: 'லைட்',
    dark: 'டார்க்',
    system: 'சிஸ்டம்',
    notifications: 'அறிவிப்புகள்',
    enableNotifications: 'அறிவிப்புகளை இயக்கு',
    disableNotifications: 'அறிவிப்புகளை முடக்கு',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    about: 'பற்றி',
    version: 'பதிப்பு 1.0.0',
    copyright: '© 2023 வியாபாரி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    poweredBy: 'வியாபாரி மூலம் இயக்கப்படுகிறது',
    madeWithLove: 'இந்தியாவில் ❤️ உடன் உருவாக்கப்பட்டது',
    contactSupport: 'ஆதரவைத் தொடர்பு கொள்ளுங்கள்',
    reportBug: 'பிழையைப் புகாரளிக்கவும்',
    shareApp: 'பயன்பாட்டைப் பகிரவும்',
    rateApp: 'பயன்பாட்டை மதிப்பிடவும்',
    followUs: 'எங்களைப் பின்தொடரவும்',
  }
};
